dyn_init – MPAS Dynamical Core
dyn_init Subroutine
89 statements
Source File
public subroutine dyn_init(cam_runtime_opts, dyn_in, dyn_out)
Uses
cam_initfiles
cam_logfile
phys_vars_init_check
cam_abortutils
cam_control_mod
air_composition
physics_types
string_utils
cam_pio_utils
time_manager
cam_thermo_formula
pio
cam_constituents
inic_analytic
runtime_obj
Initialize MPAS dynamical core by one of the following: 1. Setting analytic initial condition; 2. Reading initial condition from a file; 3. Restarting from a file. (KCW, 2024-05-28)
Arguments
Type Intent Optional Attributes Name
type(runtime_options), intent(in) :: cam_runtime_opts
type(dyn_import_t), intent(in) :: dyn_in
type(dyn_export_t), intent(in) :: dyn_out
Calls
Variables
Type Visibility Attributes Name Initial
character(len=std_name_len), private, allocatable :: constituent_name(:)
integer, private :: coupling_time_interval
integer, private :: i
integer, private :: ierr
logical, private, allocatable :: is_water_species(:)
type(file_desc_t), private, pointer :: pio_init_file
type(file_desc_t), private, pointer :: pio_topo_file
character(len=*), private, parameter :: subname = 'dyn_comp::dyn_init'
Source Code
    subroutine dyn_init(cam_runtime_opts, dyn_in, dyn_out)
        ! Module(s) from CAM-SIMA.
        use air_composition, only: thermodynamic_active_species_num, &
                                   thermodynamic_active_species_liq_num, &
                                   thermodynamic_active_species_ice_num, &
                                   thermodynamic_active_species_idx, thermodynamic_active_species_idx_dycore, &
                                   thermodynamic_active_species_liq_idx, thermodynamic_active_species_liq_idx_dycore, &
                                   thermodynamic_active_species_ice_idx, thermodynamic_active_species_ice_idx_dycore
        use cam_abortutils, only: check_allocate
        use cam_constituents, only: const_name, const_is_water_species, num_advected, readtrace
        use cam_control_mod, only: initial_run
        use cam_initfiles, only: initial_file_get_id, topo_file_get_id
        use cam_logfile, only: debugout_debug, debugout_info
        use cam_pio_utils, only: clean_iodesc_list
        use cam_thermo_formula, only: energy_formula_dycore, energy_formula_dycore_mpas
        use inic_analytic, only: analytic_ic_active
        use physics_types, only: dycore_energy_consistency_adjust
        use runtime_obj, only: runtime_options
        use string_utils, only: stringify
        use time_manager, only: get_step_size
        ! Module(s) from CCPP.
        use phys_vars_init_check, only: std_name_len
        ! Module(s) from external libraries.
        use pio, only: file_desc_t
        type(runtime_options), intent(in) :: cam_runtime_opts
        type(dyn_import_t), intent(in) :: dyn_in
        type(dyn_export_t), intent(in) :: dyn_out
        character(*), parameter :: subname = 'dyn_comp::dyn_init'
        character(std_name_len), allocatable :: constituent_name(:)
        integer :: coupling_time_interval
        integer :: i
        integer :: ierr
        logical, allocatable :: is_water_species(:)
        type(file_desc_t), pointer :: pio_init_file
        type(file_desc_t), pointer :: pio_topo_file
        call dyn_debug_print(debugout_debug, subname // ' entered')
        nullify(pio_init_file)
        nullify(pio_topo_file)
        ! Set the energy formula of dynamical core to MPAS for use in `cam_thermo`.
        energy_formula_dycore = energy_formula_dycore_mpas
        ! The total energy of dynamical core, which uses "MPAS formula" as set above, is not consistent with
        ! that of CAM physics, which uses "FV formula". Therefore, temperature and temperature tendency adjustments
        ! are needed at the end of each physics time step.
        dycore_energy_consistency_adjust = .true.
        allocate(constituent_name(num_advected), stat=ierr)
        call check_allocate(ierr, subname, 'constituent_name(num_advected)', 'dyn_comp', __LINE__)
        allocate(is_water_species(num_advected), stat=ierr)
        call check_allocate(ierr, subname, 'is_water_species(num_advected)', 'dyn_comp', __LINE__)
        do i = 1, num_advected
            constituent_name(i) = const_name(i)
            is_water_species(i) = const_is_water_species(i)
        end do
        call dyn_debug_print(debugout_info, 'Defining MPAS scalars and scalar tendencies')
        ! Inform MPAS about constituent names and their corresponding waterness.
        call mpas_dynamical_core % define_scalar(constituent_name, is_water_species)
        deallocate(constituent_name)
        deallocate(is_water_species)
        ! Provide mapping information between MPAS scalars and constituent names to CAM-SIMA.
        do i = 1, thermodynamic_active_species_num
            thermodynamic_active_species_idx_dycore(i) = &
                mpas_dynamical_core % map_mpas_scalar_index(thermodynamic_active_species_idx(i))
        end do
        do i = 1, thermodynamic_active_species_liq_num
            thermodynamic_active_species_liq_idx_dycore(i) = &
                mpas_dynamical_core % map_mpas_scalar_index(thermodynamic_active_species_liq_idx(i))
        end do
        do i = 1, thermodynamic_active_species_ice_num
            thermodynamic_active_species_ice_idx_dycore(i) = &
                mpas_dynamical_core % map_mpas_scalar_index(thermodynamic_active_species_ice_idx(i))
        end do
        call dyn_debug_print(debugout_debug, 'thermodynamic_active_species_num = ' // &
            stringify([thermodynamic_active_species_num]))
        call dyn_debug_print(debugout_debug, 'thermodynamic_active_species_liq_num = ' // &
            stringify([thermodynamic_active_species_liq_num]))
        call dyn_debug_print(debugout_debug, 'thermodynamic_active_species_ice_num = ' // &
            stringify([thermodynamic_active_species_ice_num]))
        call dyn_debug_print(debugout_debug, 'thermodynamic_active_species_idx_dycore = [' // &
            stringify(thermodynamic_active_species_idx_dycore) // ']')
        call dyn_debug_print(debugout_debug, 'thermodynamic_active_species_liq_idx_dycore = [' // &
            stringify(thermodynamic_active_species_liq_idx_dycore) // ']')
        call dyn_debug_print(debugout_debug, 'thermodynamic_active_species_ice_idx_dycore = [' // &
            stringify(thermodynamic_active_species_ice_idx_dycore) // ']')
        pio_init_file => initial_file_get_id()
        pio_topo_file => topo_file_get_id()
        if (initial_run) then
            ! Run type is initial run.
            call dyn_debug_print(debugout_info, 'Checking for consistency in topography data')
            call check_topography_data(pio_topo_file)
            if (analytic_ic_active()) then
                call dyn_debug_print(debugout_info, 'Initializing MPAS state variables by setting analytic initial condition')
                call set_analytic_initial_condition()
            else
                call dyn_debug_print(debugout_info, 'Initializing MPAS state variables by reading initial condition from a file')
                ! Perform default initialization for all constituents.
                ! Subsequently, they can be overridden depending on the namelist option (below) and
                ! the actual availability (checked and handled by MPAS).
                call dyn_exchange_constituent_states(direction='e', exchange=.true., conversion=.false.)
                ! Namelist option that controls if constituents are to be read from a file.
                if (readtrace) then
                    ! Read variables that belong to the "input" stream in MPAS.
                    call mpas_dynamical_core % read_write_stream(pio_init_file, 'r', 'input')
                else
                    ! Read variables that belong to the "input" stream in MPAS, excluding constituents.
                    call mpas_dynamical_core % read_write_stream(pio_init_file, 'r', 'input-scalars')
                end if
            end if
        else
            ! Run type is branch or restart run.
            call dyn_debug_print(debugout_info, 'Initializing MPAS state variables by restarting from a file')
            ! Read variables that belong to the "input" and "restart" streams in MPAS.
            call mpas_dynamical_core % read_write_stream(pio_init_file, 'r', 'input+restart')
        end if
        call clean_iodesc_list()
        call mark_variables_as_initialized()
        nullify(pio_init_file)
        nullify(pio_topo_file)
        ! This is the time interval for dynamics-physics coupling in CAM-SIMA.
        ! Each time MPAS dynamical core is called to run, it will integrate with time for this specific interval,
        ! then yield control back to the caller.
        coupling_time_interval = get_step_size()
        call dyn_debug_print(debugout_info, 'Initializing MPAS dynamical core (Phase 4/4)')
        ! Finish MPAS dynamical core initialization. After this point, MPAS dynamical core is ready for time integration.
        call mpas_dynamical_core % init_phase4(coupling_time_interval)
        call dyn_debug_print(debugout_debug, subname // ' completed')
    end subroutine dyn_init
Call graph
dyn_init calls analytic_ic_active, check_allocate, clean_iodesc_list, const_is_water_species, const_name, get_step_size, initial_file_get_id, check_topography_data, dyn_debug_print, dyn_exchange_constituent_states, dyn_mpas_define_scalar, dyn_mpas_init_phase4, dyn_mpas_map_mpas_scalar_index, dyn_mpas_read_write_stream, mark_variables_as_initialized, set_analytic_initial_condition, stringify, thermodynamic_active_species_ice_idx, thermodynamic_active_species_ice_idx_dycore, thermodynamic_active_species_idx, thermodynamic_active_species_idx_dycore, thermodynamic_active_species_liq_idx, thermodynamic_active_species_liq_idx_dycore, topo_file_get_id
check_topography_data calls check_allocate, dyn_debug_print, cam_read_field, endrun, get_variable_pointer, pio_file_is_open
dyn_debug_print calls stringify
dyn_exchange_constituent_states calls check_allocate, const_is_water_species, dyn_debug_print, dyn_mpas_map_mpas_scalar_index, cam_constituents_array, const_is_dry, endrun, get_variable_pointer, pdel, pdeldry, dyn_mpas_exchange_halo, dyn_mpas_map_constituent_index, reverse
dyn_mpas_define_scalar calls constituentnames, mpas_pool_add_dimension, mpas_pool_get_field, dyn_mpas_debug_print, dyn_mpas_get_pool_pointer, index_unique, stringify
dyn_mpas_init_phase4 calls atm_build_halo_groups, atm_mpas_init_block, attlists, exchange_halo_group, mpas_allocate_scratch_field, mpas_atm_dynamics_init, mpas_atm_set_dims, mpas_atm_threading_init, mpas_constants_compute_derived, mpas_get_clock_time, mpas_get_time, mpas_modify_att, mpas_pool_get_field, mpas_pool_initialize_time_levels, mpas_string_replace, almost_divisible, get_variable_pointer, dyn_mpas_debug_print, dyn_mpas_get_pool_pointer, stringify
dyn_mpas_read_write_stream calls mpas_closestream, mpas_pool_destroy_pool, mpas_readstream, mpas_writestream, postread_reindex, postwrite_reindex, prewrite_reindex, dyn_mpas_debug_print, dyn_mpas_exchange_halo, dyn_mpas_init_stream_with_pool, parse_stream_name
mark_variables_as_initialized calls const_name, dyn_debug_print, mark_as_initialized
set_analytic_initial_condition calls dyn_debug_print, final_shared_variables, init_shared_variables, set_mpas_state_rho_base_theta_base, set_mpas_state_rho_theta, set_mpas_state_scalars, set_mpas_state_u, set_mpas_state_w
dyn_mpas_debug_print calls stringify
dyn_mpas_exchange_halo calls mpas_pool_get_field, dyn_mpas_debug_print, stringify, mpas_dmpar_exch_halo_field, mpas_pool_get_field_info
dyn_mpas_get_pool_pointer calls mpas_pool_get_subpool
dyn_mpas_init_stream_with_pool calls mpas_pool_get_field, pio_file_is_open, dyn_mpas_debug_print, parse_stream_name, stringify, mpas_createstream, mpas_pool_add_config, mpas_pool_create_pool, mpas_streamaddfield, add_stream_attribute, dyn_mpas_check_variable_status
parse_stream_name calls index_unique, parse_stream_name_fragment
dyn_mpas_check_variable_status calls constituentnames, mpas_pool_get_field, pio_file_is_open, dyn_mpas_debug_print, stringify, pio_inq_varid, pio_inq_varndims, pio_inq_vartype
dyn_mpas_compute_edge_wind calls get_variable_pointer, dyn_mpas_debug_print, dyn_mpas_exchange_halo
dyn_mpas_get_variable_pointer_c0 calls dyn_mpas_get_pool_pointer, mpas_pool_get_array, mpas_pool_get_config
dyn_mpas_get_variable_pointer_c1 calls dyn_mpas_get_pool_pointer, mpas_pool_get_array
dyn_mpas_get_variable_pointer_i0 calls dyn_mpas_get_pool_pointer, mpas_pool_get_array, mpas_pool_get_config, mpas_pool_get_dimension
dyn_mpas_get_variable_pointer_i1 calls dyn_mpas_get_pool_pointer, mpas_pool_get_array, mpas_pool_get_dimension
dyn_mpas_get_variable_pointer_i2 calls dyn_mpas_get_pool_pointer, mpas_pool_get_array
dyn_mpas_get_variable_pointer_i3 calls dyn_mpas_get_pool_pointer, mpas_pool_get_array
dyn_mpas_get_variable_pointer_l0 calls dyn_mpas_get_pool_pointer, mpas_pool_get_config
dyn_mpas_get_variable_pointer_r0 calls dyn_mpas_get_pool_pointer, mpas_pool_get_array, mpas_pool_get_config
dyn_mpas_get_variable_pointer_r1 calls dyn_mpas_get_pool_pointer, mpas_pool_get_array
dyn_mpas_get_variable_pointer_r2 calls dyn_mpas_get_pool_pointer, mpas_pool_get_array
dyn_mpas_get_variable_pointer_r3 calls dyn_mpas_get_pool_pointer, mpas_pool_get_array
dyn_mpas_get_variable_pointer_r4 calls dyn_mpas_get_pool_pointer, mpas_pool_get_array
dyn_mpas_get_variable_pointer_r5 calls dyn_mpas_get_pool_pointer, mpas_pool_get_array