stepon_run3 – MPAS Dynamical Core
stepon_run3 Subroutine
14 statements
Source File
public subroutine stepon_run3(dtime_phys, cam_runtime_opts, cam_out, phys_state, dyn_in, dyn_out)
Uses
runtime_obj
camsrfexch
dyn_comp
ccpp_kinds
physics_types
Arguments
Type Intent Optional Attributes Name
real(kind=kind_phys), intent(in) :: dtime_phys
type(runtime_options), intent(in) :: cam_runtime_opts
type(cam_out_t), intent(in) :: cam_out
type(physics_state), intent(in) :: phys_state
type(dyn_import_t), intent(in) :: dyn_in
type(dyn_export_t), intent(in) :: dyn_out
Calls
Source Code
    subroutine stepon_run3(dtime_phys, cam_runtime_opts, cam_out, phys_state, dyn_in, dyn_out)
        ! Module(s) from CAM-SIMA.
        use camsrfexch, only: cam_out_t
        use dyn_comp, only: dyn_export_t, dyn_import_t, dyn_run
        use physics_types, only: physics_state
        use runtime_obj, only: runtime_options
        ! Module(s) from CCPP.
        use ccpp_kinds, only: kind_phys
        real(kind_phys), intent(in) :: dtime_phys
        type(runtime_options), intent(in) :: cam_runtime_opts
        type(cam_out_t), intent(in) :: cam_out
        type(physics_state), intent(in) :: phys_state
        type(dyn_import_t), intent(in) :: dyn_in
        type(dyn_export_t), intent(in) :: dyn_out
        call dyn_run()
    end subroutine stepon_run3
Call graph
stepon_run3 calls dyn_run
dyn_run calls dyn_debug_print, dyn_mpas_run
dyn_debug_print calls stringify
dyn_mpas_run calls atm_compute_output_diagnostics, atm_do_timestep, mpas_advance_clock, mpas_get_clock_time, mpas_get_time, mpas_pool_shift_time_levels, mpas_set_timeinterval, get_variable_pointer, dyn_mpas_debug_print, dyn_mpas_get_pool_pointer, stringify
dyn_mpas_debug_print calls stringify
dyn_mpas_get_pool_pointer calls mpas_pool_get_subpool
dyn_mpas_get_variable_pointer_c0 calls dyn_mpas_get_pool_pointer, mpas_pool_get_array, mpas_pool_get_config
dyn_mpas_get_variable_pointer_c1 calls dyn_mpas_get_pool_pointer, mpas_pool_get_array
dyn_mpas_get_variable_pointer_i0 calls dyn_mpas_get_pool_pointer, mpas_pool_get_array, mpas_pool_get_config, mpas_pool_get_dimension
dyn_mpas_get_variable_pointer_i1 calls dyn_mpas_get_pool_pointer, mpas_pool_get_array, mpas_pool_get_dimension
dyn_mpas_get_variable_pointer_i2 calls dyn_mpas_get_pool_pointer, mpas_pool_get_array
dyn_mpas_get_variable_pointer_i3 calls dyn_mpas_get_pool_pointer, mpas_pool_get_array
dyn_mpas_get_variable_pointer_l0 calls dyn_mpas_get_pool_pointer, mpas_pool_get_config
dyn_mpas_get_variable_pointer_r0 calls dyn_mpas_get_pool_pointer, mpas_pool_get_array, mpas_pool_get_config
dyn_mpas_get_variable_pointer_r1 calls dyn_mpas_get_pool_pointer, mpas_pool_get_array
dyn_mpas_get_variable_pointer_r2 calls dyn_mpas_get_pool_pointer, mpas_pool_get_array
dyn_mpas_get_variable_pointer_r3 calls dyn_mpas_get_pool_pointer, mpas_pool_get_array
dyn_mpas_get_variable_pointer_r4 calls dyn_mpas_get_pool_pointer, mpas_pool_get_array
dyn_mpas_get_variable_pointer_r5 calls dyn_mpas_get_pool_pointer, mpas_pool_get_array